#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CoAPNonIP.Android.Resource", IsApplication=true)]

namespace CoAPNonIP.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int distancearray = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int extraInformation = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int air_force_blue = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int algae_green = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int alice_blue = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int alien_green = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int almond = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int amber = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int american_rose = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int amethyst = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int android_green = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int anti_flash_white = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int antique_brass = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int antique_fuchsia = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int antique_white = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int apple_green = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int apricot = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int aqua = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int aqua_marine = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int army_brown = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int army_green = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int ash_grey = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int asparagus = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int atomic_tangerine = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int aureolin = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int aurometalsaurus = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int avocado_green = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int awesome = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int aztech_purple = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int azure = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int azure_mist_web = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int baby_blue = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int baby_blue_eyes = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int baby_pink = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int ball_blue = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int banana_mania = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int banana_yellow = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int bashful_pink = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int basket_ball_orange = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int battleship_grey = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int bazaar = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int bean_red = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int beaver = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int bee_yellow = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int beer = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int beetle_green = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int beige = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int bisque = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int bistre = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int bittersweet = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int black = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int black_cat = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int black_cow = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int black_eel = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int blanched_almond = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int blanchedalmond = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int bleu_de_france = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int blizzard_blue = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int blond = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int blood_red = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int blossom_pink = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int blue = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int blue_angel = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int blue_bell = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int blue_diamond = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int blue_dress = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int blue_eyes = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int blue_gray = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int blue_green = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int blue_hosta = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int blue_ivy = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int blue_jay = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int blue_koi = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int blue_lagoon = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int blue_lotus = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int blue_orchid = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int blue_purple = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int blue_ribbon = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public const int blue_whale = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public const int blue_zircon = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int blueberry_blue = 2130968654;
			
			// aapt resource value: 0x7f04004f
			public const int blush = 2130968655;
			
			// aapt resource value: 0x7f040050
			public const int blush_pink = 2130968656;
			
			// aapt resource value: 0x7f040051
			public const int blush_red = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int bole = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int bondi_blue = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int bone = 2130968660;
			
			// aapt resource value: 0x7f040055
			public const int bottle_green = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int boysenberry = 2130968662;
			
			// aapt resource value: 0x7f040057
			public const int brandeis_blue = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int brass = 2130968664;
			
			// aapt resource value: 0x7f040059
			public const int brick_red = 2130968665;
			
			// aapt resource value: 0x7f04005a
			public const int bright_cerulean = 2130968666;
			
			// aapt resource value: 0x7f04005b
			public const int bright_gold = 2130968667;
			
			// aapt resource value: 0x7f04005c
			public const int bright_green = 2130968668;
			
			// aapt resource value: 0x7f04005d
			public const int bright_lavender = 2130968669;
			
			// aapt resource value: 0x7f04005e
			public const int bright_maroon = 2130968670;
			
			// aapt resource value: 0x7f04005f
			public const int bright_neon_pink = 2130968671;
			
			// aapt resource value: 0x7f040060
			public const int bright_pink = 2130968672;
			
			// aapt resource value: 0x7f040061
			public const int bright_turquoise = 2130968673;
			
			// aapt resource value: 0x7f040062
			public const int bright_ube = 2130968674;
			
			// aapt resource value: 0x7f040063
			public const int brilliant_lavender = 2130968675;
			
			// aapt resource value: 0x7f040064
			public const int brilliant_rose = 2130968676;
			
			// aapt resource value: 0x7f040065
			public const int brink_pink = 2130968677;
			
			// aapt resource value: 0x7f040066
			public const int british_racing_green = 2130968678;
			
			// aapt resource value: 0x7f040067
			public const int bronze = 2130968679;
			
			// aapt resource value: 0x7f040068
			public const int brown_bear = 2130968680;
			
			// aapt resource value: 0x7f040069
			public const int brown_sugar = 2130968681;
			
			// aapt resource value: 0x7f04006a
			public const int bubble_gum = 2130968682;
			
			// aapt resource value: 0x7f04006b
			public const int bubbles = 2130968683;
			
			// aapt resource value: 0x7f04006c
			public const int buff = 2130968684;
			
			// aapt resource value: 0x7f04006d
			public const int bulgarian_rose = 2130968685;
			
			// aapt resource value: 0x7f04006e
			public const int burgundy = 2130968686;
			
			// aapt resource value: 0x7f04006f
			public const int burlywood = 2130968687;
			
			// aapt resource value: 0x7f040070
			public const int burnt_orange = 2130968688;
			
			// aapt resource value: 0x7f040071
			public const int burnt_pink = 2130968689;
			
			// aapt resource value: 0x7f040072
			public const int burnt_sienna = 2130968690;
			
			// aapt resource value: 0x7f040073
			public const int burnt_umber = 2130968691;
			
			// aapt resource value: 0x7f040074
			public const int butterfly_blue = 2130968692;
			
			// aapt resource value: 0x7f040075
			public const int byzantine = 2130968693;
			
			// aapt resource value: 0x7f040076
			public const int byzantium = 2130968694;
			
			// aapt resource value: 0x7f040077
			public const int cadet = 2130968695;
			
			// aapt resource value: 0x7f040078
			public const int cadet_blue = 2130968696;
			
			// aapt resource value: 0x7f040079
			public const int cadet_grey = 2130968697;
			
			// aapt resource value: 0x7f04007a
			public const int cadillac_pink = 2130968698;
			
			// aapt resource value: 0x7f04007b
			public const int cadmium_green = 2130968699;
			
			// aapt resource value: 0x7f04007c
			public const int cadmium_orange = 2130968700;
			
			// aapt resource value: 0x7f04007d
			public const int cadmium_red = 2130968701;
			
			// aapt resource value: 0x7f04007e
			public const int cadmium_yellow = 2130968702;
			
			// aapt resource value: 0x7f04007f
			public const int cafe_noir = 2130968703;
			
			// aapt resource value: 0x7f040080
			public const int cal_poly_pomona_green = 2130968704;
			
			// aapt resource value: 0x7f040081
			public const int cambridge_blue = 2130968705;
			
			// aapt resource value: 0x7f040082
			public const int camel_brown = 2130968706;
			
			// aapt resource value: 0x7f040083
			public const int camouflage_green = 2130968707;
			
			// aapt resource value: 0x7f040084
			public const int canary = 2130968708;
			
			// aapt resource value: 0x7f040085
			public const int canary_yellow = 2130968709;
			
			// aapt resource value: 0x7f040086
			public const int candy_apple_red = 2130968710;
			
			// aapt resource value: 0x7f040087
			public const int candy_pink = 2130968711;
			
			// aapt resource value: 0x7f040088
			public const int cantaloupe = 2130968712;
			
			// aapt resource value: 0x7f040089
			public const int capri = 2130968713;
			
			// aapt resource value: 0x7f04008a
			public const int caput_mortuum = 2130968714;
			
			// aapt resource value: 0x7f04008b
			public const int caramel = 2130968715;
			
			// aapt resource value: 0x7f04008c
			public const int carbon_gray = 2130968716;
			
			// aapt resource value: 0x7f04008d
			public const int cardinal = 2130968717;
			
			// aapt resource value: 0x7f04008e
			public const int caribbean_green = 2130968718;
			
			// aapt resource value: 0x7f04008f
			public const int carmine = 2130968719;
			
			// aapt resource value: 0x7f040090
			public const int carmine_pink = 2130968720;
			
			// aapt resource value: 0x7f040091
			public const int carmine_red = 2130968721;
			
			// aapt resource value: 0x7f040092
			public const int carnation_pink_one = 2130968722;
			
			// aapt resource value: 0x7f040093
			public const int carnation_pink_three = 2130968723;
			
			// aapt resource value: 0x7f040094
			public const int carnation_pink_two = 2130968724;
			
			// aapt resource value: 0x7f040095
			public const int carolina_blue = 2130968725;
			
			// aapt resource value: 0x7f040096
			public const int carrot_orange = 2130968726;
			
			// aapt resource value: 0x7f040097
			public const int celadon = 2130968727;
			
			// aapt resource value: 0x7f040098
			public const int celeste = 2130968728;
			
			// aapt resource value: 0x7f040099
			public const int celestial_blue = 2130968729;
			
			// aapt resource value: 0x7f04009a
			public const int cerise_pink = 2130968730;
			
			// aapt resource value: 0x7f04009b
			public const int cerulean = 2130968731;
			
			// aapt resource value: 0x7f04009c
			public const int cerulean_blue = 2130968732;
			
			// aapt resource value: 0x7f04009d
			public const int cg_blue = 2130968733;
			
			// aapt resource value: 0x7f04009e
			public const int cg_red = 2130968734;
			
			// aapt resource value: 0x7f04009f
			public const int chamoisee = 2130968735;
			
			// aapt resource value: 0x7f0400a0
			public const int champagne = 2130968736;
			
			// aapt resource value: 0x7f0400a1
			public const int charcoal = 2130968737;
			
			// aapt resource value: 0x7f0400a2
			public const int chartreuse = 2130968738;
			
			// aapt resource value: 0x7f0400a3
			public const int cherry = 2130968739;
			
			// aapt resource value: 0x7f0400a4
			public const int cherry_blossom_pink = 2130968740;
			
			// aapt resource value: 0x7f0400a5
			public const int cherry_red = 2130968741;
			
			// aapt resource value: 0x7f0400a6
			public const int chestnut = 2130968742;
			
			// aapt resource value: 0x7f0400a7
			public const int chestnut_red = 2130968743;
			
			// aapt resource value: 0x7f0400a8
			public const int chilli_pepper = 2130968744;
			
			// aapt resource value: 0x7f0400a9
			public const int chocolate = 2130968745;
			
			// aapt resource value: 0x7f0400aa
			public const int chrome_yellow = 2130968746;
			
			// aapt resource value: 0x7f0400ab
			public const int cinereous = 2130968747;
			
			// aapt resource value: 0x7f0400ac
			public const int cinnabar = 2130968748;
			
			// aapt resource value: 0x7f0400ad
			public const int citrine = 2130968749;
			
			// aapt resource value: 0x7f0400ae
			public const int classic_rose = 2130968750;
			
			// aapt resource value: 0x7f0400af
			public const int cloudy_gray = 2130968751;
			
			// aapt resource value: 0x7f0400b0
			public const int clover_green = 2130968752;
			
			// aapt resource value: 0x7f0400b1
			public const int cobalt = 2130968753;
			
			// aapt resource value: 0x7f0400b2
			public const int cobalt_blue = 2130968754;
			
			// aapt resource value: 0x7f0400b3
			public const int coffee = 2130968755;
			
			// aapt resource value: 0x7f0400b4
			public const int columbia_blue = 2130968756;
			
			// aapt resource value: 0x7f0400b5
			public const int construction_cone_orange = 2130968757;
			
			// aapt resource value: 0x7f0400b6
			public const int cookie_brown = 2130968758;
			
			// aapt resource value: 0x7f0400b7
			public const int cool_black = 2130968759;
			
			// aapt resource value: 0x7f0400b8
			public const int cool_grey = 2130968760;
			
			// aapt resource value: 0x7f0400b9
			public const int copper = 2130968761;
			
			// aapt resource value: 0x7f0400ba
			public const int copper_rose = 2130968762;
			
			// aapt resource value: 0x7f0400bb
			public const int coquelicot = 2130968763;
			
			// aapt resource value: 0x7f0400bc
			public const int coral = 2130968764;
			
			// aapt resource value: 0x7f0400bd
			public const int coral_blue = 2130968765;
			
			// aapt resource value: 0x7f0400be
			public const int coral_pink = 2130968766;
			
			// aapt resource value: 0x7f0400bf
			public const int coral_red = 2130968767;
			
			// aapt resource value: 0x7f0400c0
			public const int cordovan = 2130968768;
			
			// aapt resource value: 0x7f0400c1
			public const int corn = 2130968769;
			
			// aapt resource value: 0x7f0400c2
			public const int corn_yellow = 2130968770;
			
			// aapt resource value: 0x7f0400c3
			public const int cornell_red = 2130968771;
			
			// aapt resource value: 0x7f0400c4
			public const int cornflower = 2130968772;
			
			// aapt resource value: 0x7f0400c5
			public const int cornflower_blue = 2130968773;
			
			// aapt resource value: 0x7f0400c6
			public const int cornsilk = 2130968774;
			
			// aapt resource value: 0x7f0400c7
			public const int cosmic_latte = 2130968775;
			
			// aapt resource value: 0x7f0400c8
			public const int cotton_candy = 2130968776;
			
			// aapt resource value: 0x7f0400c9
			public const int cranberry = 2130968777;
			
			// aapt resource value: 0x7f0400ca
			public const int cream = 2130968778;
			
			// aapt resource value: 0x7f0400cb
			public const int crimson = 2130968779;
			
			// aapt resource value: 0x7f0400cc
			public const int crimson_glory = 2130968780;
			
			// aapt resource value: 0x7f0400cd
			public const int crimson_red = 2130968781;
			
			// aapt resource value: 0x7f0400ce
			public const int crocus_purple = 2130968782;
			
			// aapt resource value: 0x7f0400cf
			public const int crystal_blue = 2130968783;
			
			// aapt resource value: 0x7f0400d0
			public const int cyan = 2130968784;
			
			// aapt resource value: 0x7f0400d1
			public const int cyan_opaque = 2130968785;
			
			// aapt resource value: 0x7f0400d2
			public const int daffodil = 2130968786;
			
			// aapt resource value: 0x7f0400d3
			public const int dandelion = 2130968787;
			
			// aapt resource value: 0x7f0400d4
			public const int dark_blue = 2130968788;
			
			// aapt resource value: 0x7f0400d5
			public const int dark_brown = 2130968789;
			
			// aapt resource value: 0x7f0400d6
			public const int dark_byzantium = 2130968790;
			
			// aapt resource value: 0x7f0400d7
			public const int dark_candy_apple_red = 2130968791;
			
			// aapt resource value: 0x7f0400d8
			public const int dark_cerulean = 2130968792;
			
			// aapt resource value: 0x7f0400d9
			public const int dark_chestnut = 2130968793;
			
			// aapt resource value: 0x7f0400da
			public const int dark_coral = 2130968794;
			
			// aapt resource value: 0x7f0400db
			public const int dark_cyan = 2130968795;
			
			// aapt resource value: 0x7f0400dc
			public const int dark_electric_blue = 2130968796;
			
			// aapt resource value: 0x7f0400dd
			public const int dark_forrest_green = 2130968797;
			
			// aapt resource value: 0x7f0400de
			public const int dark_goldenrod = 2130968798;
			
			// aapt resource value: 0x7f0400df
			public const int dark_gray = 2130968799;
			
			// aapt resource value: 0x7f0400e0
			public const int dark_green = 2130968800;
			
			// aapt resource value: 0x7f0400e1
			public const int dark_jungle_green = 2130968801;
			
			// aapt resource value: 0x7f0400e2
			public const int dark_khaki = 2130968802;
			
			// aapt resource value: 0x7f0400e3
			public const int dark_lavender = 2130968803;
			
			// aapt resource value: 0x7f0400e4
			public const int dark_magenta = 2130968804;
			
			// aapt resource value: 0x7f0400e5
			public const int dark_midnight_blue = 2130968805;
			
			// aapt resource value: 0x7f0400e6
			public const int dark_olive_green = 2130968806;
			
			// aapt resource value: 0x7f0400e7
			public const int dark_orange = 2130968807;
			
			// aapt resource value: 0x7f0400e8
			public const int dark_orchid = 2130968808;
			
			// aapt resource value: 0x7f0400e9
			public const int dark_pastel_blue = 2130968809;
			
			// aapt resource value: 0x7f0400ea
			public const int dark_pastel_green = 2130968810;
			
			// aapt resource value: 0x7f0400eb
			public const int dark_pastel_purple = 2130968811;
			
			// aapt resource value: 0x7f0400ec
			public const int dark_pastel_red = 2130968812;
			
			// aapt resource value: 0x7f0400ed
			public const int dark_pink = 2130968813;
			
			// aapt resource value: 0x7f0400ee
			public const int dark_powder_blue = 2130968814;
			
			// aapt resource value: 0x7f0400ef
			public const int dark_raspberry = 2130968815;
			
			// aapt resource value: 0x7f0400f0
			public const int dark_red = 2130968816;
			
			// aapt resource value: 0x7f0400f1
			public const int dark_salmon = 2130968817;
			
			// aapt resource value: 0x7f0400f2
			public const int dark_scarlet = 2130968818;
			
			// aapt resource value: 0x7f0400f3
			public const int dark_sea_green = 2130968819;
			
			// aapt resource value: 0x7f0400f4
			public const int dark_sienna = 2130968820;
			
			// aapt resource value: 0x7f0400f5
			public const int dark_slate_blue = 2130968821;
			
			// aapt resource value: 0x7f0400f6
			public const int dark_slate_gray = 2130968822;
			
			// aapt resource value: 0x7f0400f7
			public const int dark_spring_green = 2130968823;
			
			// aapt resource value: 0x7f0400f8
			public const int dark_tan = 2130968824;
			
			// aapt resource value: 0x7f0400f9
			public const int dark_tangerine = 2130968825;
			
			// aapt resource value: 0x7f0400fa
			public const int dark_terra_cotta = 2130968826;
			
			// aapt resource value: 0x7f0400fb
			public const int dark_turquoise = 2130968827;
			
			// aapt resource value: 0x7f0400fc
			public const int dark_violet = 2130968828;
			
			// aapt resource value: 0x7f0400fd
			public const int dartmouth_green = 2130968829;
			
			// aapt resource value: 0x7f0400fe
			public const int davy_grey = 2130968830;
			
			// aapt resource value: 0x7f0400ff
			public const int debian_red = 2130968831;
			
			// aapt resource value: 0x7f040100
			public const int deep_carmine = 2130968832;
			
			// aapt resource value: 0x7f040101
			public const int deep_carmine_pink = 2130968833;
			
			// aapt resource value: 0x7f040102
			public const int deep_carrot_orange = 2130968834;
			
			// aapt resource value: 0x7f040103
			public const int deep_cerise = 2130968835;
			
			// aapt resource value: 0x7f040104
			public const int deep_champagne = 2130968836;
			
			// aapt resource value: 0x7f040105
			public const int deep_chestnut = 2130968837;
			
			// aapt resource value: 0x7f040106
			public const int deep_coffee = 2130968838;
			
			// aapt resource value: 0x7f040107
			public const int deep_fuchsia = 2130968839;
			
			// aapt resource value: 0x7f040108
			public const int deep_jungle_green = 2130968840;
			
			// aapt resource value: 0x7f040109
			public const int deep_lilac = 2130968841;
			
			// aapt resource value: 0x7f04010a
			public const int deep_magenta = 2130968842;
			
			// aapt resource value: 0x7f04010b
			public const int deep_peach = 2130968843;
			
			// aapt resource value: 0x7f04010c
			public const int deep_pink = 2130968844;
			
			// aapt resource value: 0x7f04010d
			public const int deep_saffron = 2130968845;
			
			// aapt resource value: 0x7f04010e
			public const int deep_sky_blue = 2130968846;
			
			// aapt resource value: 0x7f04010f
			public const int denim = 2130968847;
			
			// aapt resource value: 0x7f040110
			public const int denim_blue = 2130968848;
			
			// aapt resource value: 0x7f040111
			public const int desert_sand = 2130968849;
			
			// aapt resource value: 0x7f040112
			public const int dim_gray = 2130968850;
			
			// aapt resource value: 0x7f040113
			public const int dimorphotheca_magenta = 2130968851;
			
			// aapt resource value: 0x7f040114
			public const int dodger_blue = 2130968852;
			
			// aapt resource value: 0x7f040115
			public const int dogwood_rose = 2130968853;
			
			// aapt resource value: 0x7f040116
			public const int dollar_bill_green = 2130968854;
			
			// aapt resource value: 0x7f040117
			public const int dragon_green = 2130968855;
			
			// aapt resource value: 0x7f040118
			public const int duke_blue = 2130968856;
			
			// aapt resource value: 0x7f040119
			public const int dull_purple = 2130968857;
			
			// aapt resource value: 0x7f04011a
			public const int earth_blue = 2130968858;
			
			// aapt resource value: 0x7f04011b
			public const int earth_yellow = 2130968859;
			
			// aapt resource value: 0x7f04011c
			public const int eggplant = 2130968860;
			
			// aapt resource value: 0x7f04011d
			public const int eggshell = 2130968861;
			
			// aapt resource value: 0x7f04011e
			public const int egyptian_blue = 2130968862;
			
			// aapt resource value: 0x7f04011f
			public const int electric_blue = 2130968863;
			
			// aapt resource value: 0x7f040120
			public const int electric_crimson = 2130968864;
			
			// aapt resource value: 0x7f040121
			public const int electric_green = 2130968865;
			
			// aapt resource value: 0x7f040122
			public const int electric_indigo = 2130968866;
			
			// aapt resource value: 0x7f040123
			public const int electric_lavender = 2130968867;
			
			// aapt resource value: 0x7f040124
			public const int electric_purple = 2130968868;
			
			// aapt resource value: 0x7f040125
			public const int electric_ultramarine = 2130968869;
			
			// aapt resource value: 0x7f040126
			public const int electric_violet = 2130968870;
			
			// aapt resource value: 0x7f040127
			public const int emerald = 2130968871;
			
			// aapt resource value: 0x7f040128
			public const int emerald_green = 2130968872;
			
			// aapt resource value: 0x7f040129
			public const int eton_blue = 2130968873;
			
			// aapt resource value: 0x7f04012a
			public const int fall_leaf_brown = 2130968874;
			
			// aapt resource value: 0x7f04012b
			public const int falu_red = 2130968875;
			
			// aapt resource value: 0x7f04012c
			public const int famous = 2130968876;
			
			// aapt resource value: 0x7f04012d
			public const int fandango = 2130968877;
			
			// aapt resource value: 0x7f04012e
			public const int fashion_fuchsia = 2130968878;
			
			// aapt resource value: 0x7f04012f
			public const int fawn = 2130968879;
			
			// aapt resource value: 0x7f040130
			public const int feldgrau = 2130968880;
			
			// aapt resource value: 0x7f040131
			public const int fern = 2130968881;
			
			// aapt resource value: 0x7f040132
			public const int fern_green = 2130968882;
			
			// aapt resource value: 0x7f040133
			public const int ferrari_red = 2130968883;
			
			// aapt resource value: 0x7f040134
			public const int field_drab = 2130968884;
			
			// aapt resource value: 0x7f040135
			public const int fire_engine_red = 2130968885;
			
			// aapt resource value: 0x7f040136
			public const int firebrick = 2130968886;
			
			// aapt resource value: 0x7f040137
			public const int flame = 2130968887;
			
			// aapt resource value: 0x7f040138
			public const int flamingo_pink = 2130968888;
			
			// aapt resource value: 0x7f040139
			public const int flavescent = 2130968889;
			
			// aapt resource value: 0x7f04013a
			public const int flax = 2130968890;
			
			// aapt resource value: 0x7f04013b
			public const int floral_white = 2130968891;
			
			// aapt resource value: 0x7f04013c
			public const int fluorescent_pink = 2130968892;
			
			// aapt resource value: 0x7f04013d
			public const int fluorescent_yellow = 2130968893;
			
			// aapt resource value: 0x7f04013e
			public const int folly = 2130968894;
			
			// aapt resource value: 0x7f04013f
			public const int forest_green = 2130968895;
			
			// aapt resource value: 0x7f040140
			public const int french_beige = 2130968896;
			
			// aapt resource value: 0x7f040141
			public const int french_blue = 2130968897;
			
			// aapt resource value: 0x7f040142
			public const int french_lilac = 2130968898;
			
			// aapt resource value: 0x7f040143
			public const int french_rose = 2130968899;
			
			// aapt resource value: 0x7f040144
			public const int frog_green = 2130968900;
			
			// aapt resource value: 0x7f040145
			public const int fuchsia = 2130968901;
			
			// aapt resource value: 0x7f040146
			public const int fuchsia_pink = 2130968902;
			
			// aapt resource value: 0x7f040147
			public const int fulvous = 2130968903;
			
			// aapt resource value: 0x7f040148
			public const int fuzzy_wuzzy = 2130968904;
			
			// aapt resource value: 0x7f040149
			public const int gainsboro = 2130968905;
			
			// aapt resource value: 0x7f04014a
			public const int gamboge = 2130968906;
			
			// aapt resource value: 0x7f04014b
			public const int ghost_white = 2130968907;
			
			// aapt resource value: 0x7f04014c
			public const int ginger = 2130968908;
			
			// aapt resource value: 0x7f04014d
			public const int ginger_brown = 2130968909;
			
			// aapt resource value: 0x7f04014e
			public const int glaucous = 2130968910;
			
			// aapt resource value: 0x7f04014f
			public const int glitter = 2130968911;
			
			// aapt resource value: 0x7f040150
			public const int gold = 2130968912;
			
			// aapt resource value: 0x7f040151
			public const int golden = 2130968913;
			
			// aapt resource value: 0x7f040152
			public const int golden_brown = 2130968914;
			
			// aapt resource value: 0x7f040153
			public const int golden_poppy = 2130968915;
			
			// aapt resource value: 0x7f040154
			public const int golden_yellow = 2130968916;
			
			// aapt resource value: 0x7f040155
			public const int goldenrod = 2130968917;
			
			// aapt resource value: 0x7f040156
			public const int granite = 2130968918;
			
			// aapt resource value: 0x7f040157
			public const int granny_smith_apple = 2130968919;
			
			// aapt resource value: 0x7f040158
			public const int grape = 2130968920;
			
			// aapt resource value: 0x7f040159
			public const int grapefruit = 2130968921;
			
			// aapt resource value: 0x7f04015a
			public const int gray_asparagus = 2130968922;
			
			// aapt resource value: 0x7f04015b
			public const int gray_cloud = 2130968923;
			
			// aapt resource value: 0x7f04015c
			public const int gray_dolphin = 2130968924;
			
			// aapt resource value: 0x7f04015d
			public const int gray_goose = 2130968925;
			
			// aapt resource value: 0x7f04015e
			public const int gray_wolf = 2130968926;
			
			// aapt resource value: 0x7f04015f
			public const int grayish_turquoise = 2130968927;
			
			// aapt resource value: 0x7f040160
			public const int green_apple = 2130968928;
			
			// aapt resource value: 0x7f040161
			public const int green_blue = 2130968929;
			
			// aapt resource value: 0x7f040162
			public const int green_onion = 2130968930;
			
			// aapt resource value: 0x7f040163
			public const int green_peas = 2130968931;
			
			// aapt resource value: 0x7f040164
			public const int green_snake = 2130968932;
			
			// aapt resource value: 0x7f040165
			public const int green_thumb = 2130968933;
			
			// aapt resource value: 0x7f040166
			public const int green_yellow = 2130968934;
			
			// aapt resource value: 0x7f040167
			public const int greenish_blue = 2130968935;
			
			// aapt resource value: 0x7f040168
			public const int grey = 2130968936;
			
			// aapt resource value: 0x7f040169
			public const int grullo = 2130968937;
			
			// aapt resource value: 0x7f04016a
			public const int gunmetal = 2130968938;
			
			// aapt resource value: 0x7f04016b
			public const int guppie_green = 2130968939;
			
			// aapt resource value: 0x7f04016c
			public const int halaya_ube = 2130968940;
			
			// aapt resource value: 0x7f04016d
			public const int halloween_orange = 2130968941;
			
			// aapt resource value: 0x7f04016e
			public const int han_blue = 2130968942;
			
			// aapt resource value: 0x7f04016f
			public const int han_purple = 2130968943;
			
			// aapt resource value: 0x7f040170
			public const int hansa_yellow = 2130968944;
			
			// aapt resource value: 0x7f040171
			public const int harlequin = 2130968945;
			
			// aapt resource value: 0x7f040172
			public const int harvard_crimson = 2130968946;
			
			// aapt resource value: 0x7f040173
			public const int harvest_gold = 2130968947;
			
			// aapt resource value: 0x7f040174
			public const int hazel_green = 2130968948;
			
			// aapt resource value: 0x7f040175
			public const int heliotrope = 2130968949;
			
			// aapt resource value: 0x7f040176
			public const int heliotrope_purple = 2130968950;
			
			// aapt resource value: 0x7f040177
			public const int hollywood_cerise = 2130968951;
			
			// aapt resource value: 0x7f040178
			public const int honeydew = 2130968952;
			
			// aapt resource value: 0x7f040179
			public const int hooker_green = 2130968953;
			
			// aapt resource value: 0x7f04017a
			public const int hot_magenta = 2130968954;
			
			// aapt resource value: 0x7f04017b
			public const int hot_pink = 2130968955;
			
			// aapt resource value: 0x7f04017c
			public const int hummingbird_green = 2130968956;
			
			// aapt resource value: 0x7f04017d
			public const int hunter_green = 2130968957;
			
			// aapt resource value: 0x7f04017e
			public const int iceberg = 2130968958;
			
			// aapt resource value: 0x7f04017f
			public const int icterine = 2130968959;
			
			// aapt resource value: 0x7f040180
			public const int iguana_green = 2130968960;
			
			// aapt resource value: 0x7f040181
			public const int inchworm = 2130968961;
			
			// aapt resource value: 0x7f040182
			public const int india_green = 2130968962;
			
			// aapt resource value: 0x7f040183
			public const int indian_yellow = 2130968963;
			
			// aapt resource value: 0x7f040184
			public const int indigo = 2130968964;
			
			// aapt resource value: 0x7f040185
			public const int international_klein_blue = 2130968965;
			
			// aapt resource value: 0x7f040186
			public const int international_orange = 2130968966;
			
			// aapt resource value: 0x7f040187
			public const int iris = 2130968967;
			
			// aapt resource value: 0x7f040188
			public const int isabelline = 2130968968;
			
			// aapt resource value: 0x7f040189
			public const int islamic_green = 2130968969;
			
			// aapt resource value: 0x7f04018a
			public const int ivory = 2130968970;
			
			// aapt resource value: 0x7f04018b
			public const int jade = 2130968971;
			
			// aapt resource value: 0x7f04018c
			public const int jasmine = 2130968972;
			
			// aapt resource value: 0x7f04018d
			public const int jasmine_purple = 2130968973;
			
			// aapt resource value: 0x7f04018e
			public const int jasper = 2130968974;
			
			// aapt resource value: 0x7f04018f
			public const int jazzberry_jam = 2130968975;
			
			// aapt resource value: 0x7f040190
			public const int jeans_blue = 2130968976;
			
			// aapt resource value: 0x7f040191
			public const int jellyfish = 2130968977;
			
			// aapt resource value: 0x7f040192
			public const int jet_gray = 2130968978;
			
			// aapt resource value: 0x7f040193
			public const int jonquil = 2130968979;
			
			// aapt resource value: 0x7f040194
			public const int june_bud = 2130968980;
			
			// aapt resource value: 0x7f040195
			public const int jungle_green = 2130968981;
			
			// aapt resource value: 0x7f040196
			public const int kelly_green = 2130968982;
			
			// aapt resource value: 0x7f040197
			public const int khaki = 2130968983;
			
			// aapt resource value: 0x7f040198
			public const int khaki_rose = 2130968984;
			
			// aapt resource value: 0x7f040199
			public const int ku_crimson = 2130968985;
			
			// aapt resource value: 0x7f04019a
			public const int la_salle_green = 2130968986;
			
			// aapt resource value: 0x7f04019b
			public const int languid_lavender = 2130968987;
			
			// aapt resource value: 0x7f04019c
			public const int lapis_blue = 2130968988;
			
			// aapt resource value: 0x7f04019d
			public const int lapis_lazuli = 2130968989;
			
			// aapt resource value: 0x7f04019e
			public const int laser_lemon = 2130968990;
			
			// aapt resource value: 0x7f04019f
			public const int laurel_green = 2130968991;
			
			// aapt resource value: 0x7f0401a0
			public const int lava = 2130968992;
			
			// aapt resource value: 0x7f0401a1
			public const int lava_red = 2130968993;
			
			// aapt resource value: 0x7f0401a2
			public const int lavender = 2130968994;
			
			// aapt resource value: 0x7f0401a3
			public const int lavender_blue = 2130968995;
			
			// aapt resource value: 0x7f0401a4
			public const int lavender_blush = 2130968996;
			
			// aapt resource value: 0x7f0401a5
			public const int lavender_gray = 2130968997;
			
			// aapt resource value: 0x7f0401a6
			public const int lavender_indigo = 2130968998;
			
			// aapt resource value: 0x7f0401a7
			public const int lavender_magenta = 2130968999;
			
			// aapt resource value: 0x7f0401a8
			public const int lavender_pink = 2130969000;
			
			// aapt resource value: 0x7f0401a9
			public const int lavender_pinocchio = 2130969001;
			
			// aapt resource value: 0x7f0401aa
			public const int lavender_purple = 2130969002;
			
			// aapt resource value: 0x7f0401ab
			public const int lavender_rose = 2130969003;
			
			// aapt resource value: 0x7f0401ac
			public const int lawn_green = 2130969004;
			
			// aapt resource value: 0x7f0401ad
			public const int lemon = 2130969005;
			
			// aapt resource value: 0x7f0401ae
			public const int lemon_chiffon = 2130969006;
			
			// aapt resource value: 0x7f0401af
			public const int lemon_lime = 2130969007;
			
			// aapt resource value: 0x7f0401b0
			public const int lemon_yellow = 2130969008;
			
			// aapt resource value: 0x7f0401b1
			public const int light_apricot = 2130969009;
			
			// aapt resource value: 0x7f0401b2
			public const int light_aquamarine = 2130969010;
			
			// aapt resource value: 0x7f0401b3
			public const int light_blue = 2130969011;
			
			// aapt resource value: 0x7f0401b4
			public const int light_brown = 2130969012;
			
			// aapt resource value: 0x7f0401b5
			public const int light_carmine_pink = 2130969013;
			
			// aapt resource value: 0x7f0401b6
			public const int light_coral = 2130969014;
			
			// aapt resource value: 0x7f0401b7
			public const int light_cornflower_blue = 2130969015;
			
			// aapt resource value: 0x7f0401b8
			public const int light_crimson = 2130969016;
			
			// aapt resource value: 0x7f0401b9
			public const int light_cyan = 2130969017;
			
			// aapt resource value: 0x7f0401ba
			public const int light_fuchsia_pink = 2130969018;
			
			// aapt resource value: 0x7f0401bb
			public const int light_goldenrod_yellow = 2130969019;
			
			// aapt resource value: 0x7f0401bc
			public const int light_gray = 2130969020;
			
			// aapt resource value: 0x7f0401bd
			public const int light_green = 2130969021;
			
			// aapt resource value: 0x7f0401be
			public const int light_jade = 2130969022;
			
			// aapt resource value: 0x7f0401bf
			public const int light_khaki = 2130969023;
			
			// aapt resource value: 0x7f0401c0
			public const int light_pastel_purple = 2130969024;
			
			// aapt resource value: 0x7f0401c1
			public const int light_pink = 2130969025;
			
			// aapt resource value: 0x7f0401c2
			public const int light_salmon = 2130969026;
			
			// aapt resource value: 0x7f0401c3
			public const int light_salmon_pink = 2130969027;
			
			// aapt resource value: 0x7f0401c4
			public const int light_sea_green = 2130969028;
			
			// aapt resource value: 0x7f0401c5
			public const int light_sky_blue = 2130969029;
			
			// aapt resource value: 0x7f0401c6
			public const int light_slate = 2130969030;
			
			// aapt resource value: 0x7f0401c7
			public const int light_slate_blue = 2130969031;
			
			// aapt resource value: 0x7f0401c8
			public const int light_slate_gray = 2130969032;
			
			// aapt resource value: 0x7f0401c9
			public const int light_steel_blue = 2130969033;
			
			// aapt resource value: 0x7f0401ca
			public const int light_taupe = 2130969034;
			
			// aapt resource value: 0x7f0401cb
			public const int light_thulian_pink = 2130969035;
			
			// aapt resource value: 0x7f0401cc
			public const int light_yellow = 2130969036;
			
			// aapt resource value: 0x7f0401cd
			public const int lilac = 2130969037;
			
			// aapt resource value: 0x7f0401ce
			public const int lime_green = 2130969038;
			
			// aapt resource value: 0x7f0401cf
			public const int lincoln_green = 2130969039;
			
			// aapt resource value: 0x7f0401d0
			public const int linen = 2130969040;
			
			// aapt resource value: 0x7f0401d1
			public const int lipstick_pink = 2130969041;
			
			// aapt resource value: 0x7f0401d2
			public const int liver = 2130969042;
			
			// aapt resource value: 0x7f0401d3
			public const int love_red = 2130969043;
			
			// aapt resource value: 0x7f0401d4
			public const int lovely_purple = 2130969044;
			
			// aapt resource value: 0x7f0401d5
			public const int lust = 2130969045;
			
			// aapt resource value: 0x7f0401d6
			public const int macaroni_and_cheese = 2130969046;
			
			// aapt resource value: 0x7f0401d7
			public const int magenta = 2130969047;
			
			// aapt resource value: 0x7f0401d8
			public const int magic_mint = 2130969048;
			
			// aapt resource value: 0x7f0401d9
			public const int magnolia = 2130969049;
			
			// aapt resource value: 0x7f0401da
			public const int mahogany = 2130969050;
			
			// aapt resource value: 0x7f0401db
			public const int maize = 2130969051;
			
			// aapt resource value: 0x7f0401dc
			public const int majorelle_blue = 2130969052;
			
			// aapt resource value: 0x7f0401dd
			public const int malachite = 2130969053;
			
			// aapt resource value: 0x7f0401de
			public const int manatee = 2130969054;
			
			// aapt resource value: 0x7f0401df
			public const int mango_orange = 2130969055;
			
			// aapt resource value: 0x7f0401e0
			public const int mango_tango = 2130969056;
			
			// aapt resource value: 0x7f0401e1
			public const int mantis = 2130969057;
			
			// aapt resource value: 0x7f0401e2
			public const int marble_blue = 2130969058;
			
			// aapt resource value: 0x7f0401e3
			public const int maroon = 2130969059;
			
			// aapt resource value: 0x7f0401e4
			public const int mascaw_blue_green = 2130969060;
			
			// aapt resource value: 0x7f0401e5
			public const int mauve = 2130969061;
			
			// aapt resource value: 0x7f0401e6
			public const int mauvelous = 2130969062;
			
			// aapt resource value: 0x7f0401e7
			public const int maya_blue = 2130969063;
			
			// aapt resource value: 0x7f0401e8
			public const int meat_brown = 2130969064;
			
			// aapt resource value: 0x7f0401e9
			public const int medium_aquamarine = 2130969065;
			
			// aapt resource value: 0x7f0401ea
			public const int medium_blue = 2130969066;
			
			// aapt resource value: 0x7f0401eb
			public const int medium_candy_apple_red = 2130969067;
			
			// aapt resource value: 0x7f0401ec
			public const int medium_champagne = 2130969068;
			
			// aapt resource value: 0x7f0401ed
			public const int medium_electric_blue = 2130969069;
			
			// aapt resource value: 0x7f0401ee
			public const int medium_forest_green = 2130969070;
			
			// aapt resource value: 0x7f0401ef
			public const int medium_jungle_green = 2130969071;
			
			// aapt resource value: 0x7f0401f0
			public const int medium_lavender_magenta = 2130969072;
			
			// aapt resource value: 0x7f0401f1
			public const int medium_orchid = 2130969073;
			
			// aapt resource value: 0x7f0401f2
			public const int medium_persian_blue = 2130969074;
			
			// aapt resource value: 0x7f0401f3
			public const int medium_purple = 2130969075;
			
			// aapt resource value: 0x7f0401f4
			public const int medium_red_violet = 2130969076;
			
			// aapt resource value: 0x7f0401f5
			public const int medium_sea_green = 2130969077;
			
			// aapt resource value: 0x7f0401f6
			public const int medium_slate_blue = 2130969078;
			
			// aapt resource value: 0x7f0401f7
			public const int medium_spring_bud = 2130969079;
			
			// aapt resource value: 0x7f0401f8
			public const int medium_spring_green = 2130969080;
			
			// aapt resource value: 0x7f0401f9
			public const int medium_taupe = 2130969081;
			
			// aapt resource value: 0x7f0401fa
			public const int medium_teal_blue = 2130969082;
			
			// aapt resource value: 0x7f0401fb
			public const int medium_turquoise = 2130969083;
			
			// aapt resource value: 0x7f0401fc
			public const int medium_violet_red = 2130969084;
			
			// aapt resource value: 0x7f0401fd
			public const int melon = 2130969085;
			
			// aapt resource value: 0x7f0401fe
			public const int metallic_silver = 2130969086;
			
			// aapt resource value: 0x7f0401ff
			public const int midnight = 2130969087;
			
			// aapt resource value: 0x7f040200
			public const int midnight_blue = 2130969088;
			
			// aapt resource value: 0x7f040201
			public const int midnight_green = 2130969089;
			
			// aapt resource value: 0x7f040202
			public const int mikado_yellow = 2130969090;
			
			// aapt resource value: 0x7f040203
			public const int milk_white = 2130969091;
			
			// aapt resource value: 0x7f040204
			public const int mint = 2130969092;
			
			// aapt resource value: 0x7f040205
			public const int mint_cream = 2130969093;
			
			// aapt resource value: 0x7f040206
			public const int mint_green = 2130969094;
			
			// aapt resource value: 0x7f040207
			public const int mist_blue = 2130969095;
			
			// aapt resource value: 0x7f040208
			public const int misty_rose = 2130969096;
			
			// aapt resource value: 0x7f040209
			public const int moccasin = 2130969097;
			
			// aapt resource value: 0x7f04020a
			public const int mocha = 2130969098;
			
			// aapt resource value: 0x7f04020b
			public const int moonstone_blue = 2130969099;
			
			// aapt resource value: 0x7f04020c
			public const int mordant_red_19 = 2130969100;
			
			// aapt resource value: 0x7f04020d
			public const int moss_green = 2130969101;
			
			// aapt resource value: 0x7f04020e
			public const int mountain_meadow = 2130969102;
			
			// aapt resource value: 0x7f04020f
			public const int mountbatten_pink = 2130969103;
			
			// aapt resource value: 0x7f040210
			public const int msu_green = 2130969104;
			
			// aapt resource value: 0x7f040211
			public const int mulberry = 2130969105;
			
			// aapt resource value: 0x7f040212
			public const int mustard = 2130969106;
			
			// aapt resource value: 0x7f040213
			public const int myrtle = 2130969107;
			
			// aapt resource value: 0x7f040214
			public const int nadeshiko_pink = 2130969108;
			
			// aapt resource value: 0x7f040215
			public const int napier_green = 2130969109;
			
			// aapt resource value: 0x7f040216
			public const int naples_yellow = 2130969110;
			
			// aapt resource value: 0x7f040217
			public const int navajo_white = 2130969111;
			
			// aapt resource value: 0x7f040218
			public const int navy_blue = 2130969112;
			
			// aapt resource value: 0x7f040219
			public const int nebula_green = 2130969113;
			
			// aapt resource value: 0x7f04021a
			public const int neon_carrot = 2130969114;
			
			// aapt resource value: 0x7f04021b
			public const int neon_fuchsia = 2130969115;
			
			// aapt resource value: 0x7f04021c
			public const int neon_green = 2130969116;
			
			// aapt resource value: 0x7f04021d
			public const int neon_pink = 2130969117;
			
			// aapt resource value: 0x7f04021e
			public const int non_photo_blue = 2130969118;
			
			// aapt resource value: 0x7f04021f
			public const int north_texas_green = 2130969119;
			
			// aapt resource value: 0x7f040220
			public const int northern_lights_blue = 2130969120;
			
			// aapt resource value: 0x7f040221
			public const int oak_brown = 2130969121;
			
			// aapt resource value: 0x7f040222
			public const int ocean_blue = 2130969122;
			
			// aapt resource value: 0x7f040223
			public const int ocean_boat_blue = 2130969123;
			
			// aapt resource value: 0x7f040224
			public const int ochre = 2130969124;
			
			// aapt resource value: 0x7f040225
			public const int office_green = 2130969125;
			
			// aapt resource value: 0x7f040226
			public const int oil = 2130969126;
			
			// aapt resource value: 0x7f040227
			public const int old_gold = 2130969127;
			
			// aapt resource value: 0x7f040228
			public const int old_lace = 2130969128;
			
			// aapt resource value: 0x7f040229
			public const int old_lavender = 2130969129;
			
			// aapt resource value: 0x7f04022a
			public const int old_mauve = 2130969130;
			
			// aapt resource value: 0x7f04022b
			public const int old_rose = 2130969131;
			
			// aapt resource value: 0x7f04022c
			public const int olive = 2130969132;
			
			// aapt resource value: 0x7f04022d
			public const int olive_drab = 2130969133;
			
			// aapt resource value: 0x7f04022e
			public const int olive_green = 2130969134;
			
			// aapt resource value: 0x7f04022f
			public const int olivine = 2130969135;
			
			// aapt resource value: 0x7f040230
			public const int onyx = 2130969136;
			
			// aapt resource value: 0x7f040231
			public const int opera_mauve = 2130969137;
			
			// aapt resource value: 0x7f040232
			public const int orange = 2130969138;
			
			// aapt resource value: 0x7f040233
			public const int orange_peel = 2130969139;
			
			// aapt resource value: 0x7f040234
			public const int orange_red = 2130969140;
			
			// aapt resource value: 0x7f040235
			public const int orange_salmon = 2130969141;
			
			// aapt resource value: 0x7f040236
			public const int orange_yellow = 2130969142;
			
			// aapt resource value: 0x7f040237
			public const int orchid = 2130969143;
			
			// aapt resource value: 0x7f040238
			public const int outer_space = 2130969144;
			
			// aapt resource value: 0x7f040239
			public const int outrageous_orange = 2130969145;
			
			// aapt resource value: 0x7f04023a
			public const int oxford_blue = 2130969146;
			
			// aapt resource value: 0x7f04023b
			public const int pacific_blue = 2130969147;
			
			// aapt resource value: 0x7f04023c
			public const int pakistan_green = 2130969148;
			
			// aapt resource value: 0x7f04023d
			public const int palatinate_blue = 2130969149;
			
			// aapt resource value: 0x7f04023e
			public const int palatinate_purple = 2130969150;
			
			// aapt resource value: 0x7f04023f
			public const int pale_aqua = 2130969151;
			
			// aapt resource value: 0x7f040240
			public const int pale_blue = 2130969152;
			
			// aapt resource value: 0x7f040241
			public const int pale_blue_lily = 2130969153;
			
			// aapt resource value: 0x7f040242
			public const int pale_brown = 2130969154;
			
			// aapt resource value: 0x7f040243
			public const int pale_carmine = 2130969155;
			
			// aapt resource value: 0x7f040244
			public const int pale_cerulean = 2130969156;
			
			// aapt resource value: 0x7f040245
			public const int pale_chestnut = 2130969157;
			
			// aapt resource value: 0x7f040246
			public const int pale_copper = 2130969158;
			
			// aapt resource value: 0x7f040247
			public const int pale_cornflower_blue = 2130969159;
			
			// aapt resource value: 0x7f040248
			public const int pale_gold = 2130969160;
			
			// aapt resource value: 0x7f040249
			public const int pale_goldenrod = 2130969161;
			
			// aapt resource value: 0x7f04024a
			public const int pale_green = 2130969162;
			
			// aapt resource value: 0x7f04024b
			public const int pale_lavender = 2130969163;
			
			// aapt resource value: 0x7f04024c
			public const int pale_magenta = 2130969164;
			
			// aapt resource value: 0x7f04024d
			public const int pale_pink = 2130969165;
			
			// aapt resource value: 0x7f04024e
			public const int pale_red_violet = 2130969166;
			
			// aapt resource value: 0x7f04024f
			public const int pale_robin_egg_blue = 2130969167;
			
			// aapt resource value: 0x7f040250
			public const int pale_silver = 2130969168;
			
			// aapt resource value: 0x7f040251
			public const int pale_spring_bud = 2130969169;
			
			// aapt resource value: 0x7f040252
			public const int pale_taupe = 2130969170;
			
			// aapt resource value: 0x7f040253
			public const int pansy_purple = 2130969171;
			
			// aapt resource value: 0x7f040254
			public const int papaya_orange = 2130969172;
			
			// aapt resource value: 0x7f040255
			public const int papaya_whip = 2130969173;
			
			// aapt resource value: 0x7f040256
			public const int parchment = 2130969174;
			
			// aapt resource value: 0x7f040257
			public const int paris_green = 2130969175;
			
			// aapt resource value: 0x7f040258
			public const int pastel_blue = 2130969176;
			
			// aapt resource value: 0x7f040259
			public const int pastel_brown = 2130969177;
			
			// aapt resource value: 0x7f04025a
			public const int pastel_gray = 2130969178;
			
			// aapt resource value: 0x7f04025b
			public const int pastel_green = 2130969179;
			
			// aapt resource value: 0x7f04025c
			public const int pastel_magenta = 2130969180;
			
			// aapt resource value: 0x7f04025d
			public const int pastel_orange = 2130969181;
			
			// aapt resource value: 0x7f04025e
			public const int pastel_pink = 2130969182;
			
			// aapt resource value: 0x7f04025f
			public const int pastel_purple = 2130969183;
			
			// aapt resource value: 0x7f040260
			public const int pastel_red = 2130969184;
			
			// aapt resource value: 0x7f040261
			public const int pastel_violet = 2130969185;
			
			// aapt resource value: 0x7f040262
			public const int pastel_yellow = 2130969186;
			
			// aapt resource value: 0x7f040263
			public const int payne_grey = 2130969187;
			
			// aapt resource value: 0x7f040264
			public const int peach = 2130969188;
			
			// aapt resource value: 0x7f040265
			public const int peach_puff = 2130969189;
			
			// aapt resource value: 0x7f040266
			public const int peach_yellow = 2130969190;
			
			// aapt resource value: 0x7f040267
			public const int pearl = 2130969191;
			
			// aapt resource value: 0x7f040268
			public const int pearl_aqua = 2130969192;
			
			// aapt resource value: 0x7f040269
			public const int peridot = 2130969193;
			
			// aapt resource value: 0x7f04026a
			public const int persian_blue = 2130969194;
			
			// aapt resource value: 0x7f04026b
			public const int persian_indigo = 2130969195;
			
			// aapt resource value: 0x7f04026c
			public const int persian_orange = 2130969196;
			
			// aapt resource value: 0x7f04026d
			public const int persian_pink = 2130969197;
			
			// aapt resource value: 0x7f04026e
			public const int persian_plum = 2130969198;
			
			// aapt resource value: 0x7f04026f
			public const int persian_red = 2130969199;
			
			// aapt resource value: 0x7f040270
			public const int persian_rose = 2130969200;
			
			// aapt resource value: 0x7f040271
			public const int phthalo_blue = 2130969201;
			
			// aapt resource value: 0x7f040272
			public const int phthalo_green = 2130969202;
			
			// aapt resource value: 0x7f040273
			public const int pig_pink = 2130969203;
			
			// aapt resource value: 0x7f040274
			public const int piggy_pink = 2130969204;
			
			// aapt resource value: 0x7f040275
			public const int pine_green = 2130969205;
			
			// aapt resource value: 0x7f040276
			public const int pink = 2130969206;
			
			// aapt resource value: 0x7f040277
			public const int pink_bow = 2130969207;
			
			// aapt resource value: 0x7f040278
			public const int pink_bubblegum = 2130969208;
			
			// aapt resource value: 0x7f040279
			public const int pink_cupcake = 2130969209;
			
			// aapt resource value: 0x7f04027a
			public const int pink_daisy = 2130969210;
			
			// aapt resource value: 0x7f04027b
			public const int pink_flamingo = 2130969211;
			
			// aapt resource value: 0x7f04027c
			public const int pink_lemonade = 2130969212;
			
			// aapt resource value: 0x7f04027d
			public const int pink_pearl = 2130969213;
			
			// aapt resource value: 0x7f04027e
			public const int pink_rose = 2130969214;
			
			// aapt resource value: 0x7f04027f
			public const int pink_sherbet = 2130969215;
			
			// aapt resource value: 0x7f040280
			public const int pistachio = 2130969216;
			
			// aapt resource value: 0x7f040281
			public const int pistachio_green = 2130969217;
			
			// aapt resource value: 0x7f040282
			public const int platinum = 2130969218;
			
			// aapt resource value: 0x7f040283
			public const int plum = 2130969219;
			
			// aapt resource value: 0x7f040284
			public const int plum_pie = 2130969220;
			
			// aapt resource value: 0x7f040285
			public const int plum_purple = 2130969221;
			
			// aapt resource value: 0x7f040286
			public const int plum_velvet = 2130969222;
			
			// aapt resource value: 0x7f040287
			public const int portland_orange = 2130969223;
			
			// aapt resource value: 0x7f040288
			public const int powder_blue = 2130969224;
			
			// aapt resource value: 0x7f040289
			public const int princeton_orange = 2130969225;
			
			// aapt resource value: 0x7f04028a
			public const int prussian_blue = 2130969226;
			
			// aapt resource value: 0x7f04028b
			public const int psychedelic_purple = 2130969227;
			
			// aapt resource value: 0x7f04028c
			public const int puce = 2130969228;
			
			// aapt resource value: 0x7f04028d
			public const int pumpkin = 2130969229;
			
			// aapt resource value: 0x7f04028e
			public const int pumpkin_orange = 2130969230;
			
			// aapt resource value: 0x7f04028f
			public const int purple = 2130969231;
			
			// aapt resource value: 0x7f040290
			public const int purple_amethyst = 2130969232;
			
			// aapt resource value: 0x7f040291
			public const int purple_daffodil = 2130969233;
			
			// aapt resource value: 0x7f040292
			public const int purple_dragon = 2130969234;
			
			// aapt resource value: 0x7f040293
			public const int purple_flower = 2130969235;
			
			// aapt resource value: 0x7f040294
			public const int purple_haze = 2130969236;
			
			// aapt resource value: 0x7f040295
			public const int purple_heart = 2130969237;
			
			// aapt resource value: 0x7f040296
			public const int purple_iris = 2130969238;
			
			// aapt resource value: 0x7f040297
			public const int purple_jam = 2130969239;
			
			// aapt resource value: 0x7f040298
			public const int purple_mimosa = 2130969240;
			
			// aapt resource value: 0x7f040299
			public const int purple_monster = 2130969241;
			
			// aapt resource value: 0x7f04029a
			public const int purple_mountain_majesty = 2130969242;
			
			// aapt resource value: 0x7f04029b
			public const int purple_pizzazz = 2130969243;
			
			// aapt resource value: 0x7f04029c
			public const int purple_sage_bush = 2130969244;
			
			// aapt resource value: 0x7f04029d
			public const int purple_taupe = 2130969245;
			
			// aapt resource value: 0x7f04029e
			public const int radical_red = 2130969246;
			
			// aapt resource value: 0x7f04029f
			public const int raspberry = 2130969247;
			
			// aapt resource value: 0x7f0402a0
			public const int raspberry_glace = 2130969248;
			
			// aapt resource value: 0x7f0402a1
			public const int raspberry_pink = 2130969249;
			
			// aapt resource value: 0x7f0402a2
			public const int raspberry_rose = 2130969250;
			
			// aapt resource value: 0x7f0402a3
			public const int raw_sienna = 2130969251;
			
			// aapt resource value: 0x7f0402a4
			public const int razzle_dazzle_rose = 2130969252;
			
			// aapt resource value: 0x7f0402a5
			public const int razzmatazz = 2130969253;
			
			// aapt resource value: 0x7f0402a6
			public const int red = 2130969254;
			
			// aapt resource value: 0x7f0402a7
			public const int red_brown = 2130969255;
			
			// aapt resource value: 0x7f0402a8
			public const int red_dirt = 2130969256;
			
			// aapt resource value: 0x7f0402a9
			public const int red_fox = 2130969257;
			
			// aapt resource value: 0x7f0402aa
			public const int red_orange = 2130969258;
			
			// aapt resource value: 0x7f0402ab
			public const int red_violet = 2130969259;
			
			// aapt resource value: 0x7f0402ac
			public const int red_wine = 2130969260;
			
			// aapt resource value: 0x7f0402ad
			public const int rich_black = 2130969261;
			
			// aapt resource value: 0x7f0402ae
			public const int rich_carmine = 2130969262;
			
			// aapt resource value: 0x7f0402af
			public const int rich_electric_blue = 2130969263;
			
			// aapt resource value: 0x7f0402b0
			public const int rich_lilac = 2130969264;
			
			// aapt resource value: 0x7f0402b1
			public const int rich_maroon = 2130969265;
			
			// aapt resource value: 0x7f0402b2
			public const int rifle_green = 2130969266;
			
			// aapt resource value: 0x7f0402b3
			public const int robin_egg_blue = 2130969267;
			
			// aapt resource value: 0x7f0402b4
			public const int rogue_pink = 2130969268;
			
			// aapt resource value: 0x7f0402b5
			public const int rose = 2130969269;
			
			// aapt resource value: 0x7f0402b6
			public const int rose_bonbon = 2130969270;
			
			// aapt resource value: 0x7f0402b7
			public const int rose_ebony = 2130969271;
			
			// aapt resource value: 0x7f0402b8
			public const int rose_gold = 2130969272;
			
			// aapt resource value: 0x7f0402b9
			public const int rose_madder = 2130969273;
			
			// aapt resource value: 0x7f0402ba
			public const int rose_pink = 2130969274;
			
			// aapt resource value: 0x7f0402bb
			public const int rose_quartz = 2130969275;
			
			// aapt resource value: 0x7f0402bc
			public const int rose_taupe = 2130969276;
			
			// aapt resource value: 0x7f0402bd
			public const int rose_vale = 2130969277;
			
			// aapt resource value: 0x7f0402be
			public const int rosewood = 2130969278;
			
			// aapt resource value: 0x7f0402bf
			public const int rosso_corsa = 2130969279;
			
			// aapt resource value: 0x7f0402c0
			public const int rosy_brown = 2130969280;
			
			// aapt resource value: 0x7f0402c1
			public const int rosy_finch = 2130969281;
			
			// aapt resource value: 0x7f0402c2
			public const int royal_azure = 2130969282;
			
			// aapt resource value: 0x7f0402c3
			public const int royal_blue = 2130969283;
			
			// aapt resource value: 0x7f0402c4
			public const int royal_fuchsia = 2130969284;
			
			// aapt resource value: 0x7f0402c5
			public const int royal_purple = 2130969285;
			
			// aapt resource value: 0x7f0402c6
			public const int rubber_ducky_yellow = 2130969286;
			
			// aapt resource value: 0x7f0402c7
			public const int ruby = 2130969287;
			
			// aapt resource value: 0x7f0402c8
			public const int ruby_red = 2130969288;
			
			// aapt resource value: 0x7f0402c9
			public const int ruddy = 2130969289;
			
			// aapt resource value: 0x7f0402ca
			public const int ruddy_brown = 2130969290;
			
			// aapt resource value: 0x7f0402cb
			public const int ruddy_pink = 2130969291;
			
			// aapt resource value: 0x7f0402cc
			public const int rufous = 2130969292;
			
			// aapt resource value: 0x7f0402cd
			public const int russet = 2130969293;
			
			// aapt resource value: 0x7f0402ce
			public const int rust = 2130969294;
			
			// aapt resource value: 0x7f0402cf
			public const int sacramento_state_green = 2130969295;
			
			// aapt resource value: 0x7f0402d0
			public const int saddle_brown = 2130969296;
			
			// aapt resource value: 0x7f0402d1
			public const int safety_orange = 2130969297;
			
			// aapt resource value: 0x7f0402d2
			public const int saffron = 2130969298;
			
			// aapt resource value: 0x7f0402d3
			public const int saint_patrick_blue = 2130969299;
			
			// aapt resource value: 0x7f0402d4
			public const int salad_green = 2130969300;
			
			// aapt resource value: 0x7f0402d5
			public const int salmon = 2130969301;
			
			// aapt resource value: 0x7f0402d6
			public const int salmon_pink = 2130969302;
			
			// aapt resource value: 0x7f0402d7
			public const int sand = 2130969303;
			
			// aapt resource value: 0x7f0402d8
			public const int sandstone = 2130969304;
			
			// aapt resource value: 0x7f0402d9
			public const int sandstorm = 2130969305;
			
			// aapt resource value: 0x7f0402da
			public const int sandy_brown = 2130969306;
			
			// aapt resource value: 0x7f0402db
			public const int sandy_taupe = 2130969307;
			
			// aapt resource value: 0x7f0402dc
			public const int sangria = 2130969308;
			
			// aapt resource value: 0x7f0402dd
			public const int sap_green = 2130969309;
			
			// aapt resource value: 0x7f0402de
			public const int sapphire = 2130969310;
			
			// aapt resource value: 0x7f0402df
			public const int sapphire_blue = 2130969311;
			
			// aapt resource value: 0x7f0402e0
			public const int satin_sheen_gold = 2130969312;
			
			// aapt resource value: 0x7f0402e1
			public const int scarlet = 2130969313;
			
			// aapt resource value: 0x7f0402e2
			public const int school_bus_yellow = 2130969314;
			
			// aapt resource value: 0x7f0402e3
			public const int screamin_green = 2130969315;
			
			// aapt resource value: 0x7f0402e4
			public const int sea_blue = 2130969316;
			
			// aapt resource value: 0x7f0402e5
			public const int sea_green = 2130969317;
			
			// aapt resource value: 0x7f0402e6
			public const int sea_turtle_green = 2130969318;
			
			// aapt resource value: 0x7f0402e7
			public const int seal_brown = 2130969319;
			
			// aapt resource value: 0x7f0402e8
			public const int seashell = 2130969320;
			
			// aapt resource value: 0x7f0402e9
			public const int seaweed_green = 2130969321;
			
			// aapt resource value: 0x7f0402ea
			public const int sedona = 2130969322;
			
			// aapt resource value: 0x7f0402eb
			public const int selective_yellow = 2130969323;
			
			// aapt resource value: 0x7f0402ec
			public const int sepia = 2130969324;
			
			// aapt resource value: 0x7f0402ed
			public const int shadow = 2130969325;
			
			// aapt resource value: 0x7f0402ee
			public const int shamrock = 2130969326;
			
			// aapt resource value: 0x7f0402ef
			public const int shamrock_green = 2130969327;
			
			// aapt resource value: 0x7f0402f0
			public const int shocking_orange = 2130969328;
			
			// aapt resource value: 0x7f0402f1
			public const int shocking_pink = 2130969329;
			
			// aapt resource value: 0x7f0402f2
			public const int sienna = 2130969330;
			
			// aapt resource value: 0x7f0402f3
			public const int silk_blue = 2130969331;
			
			// aapt resource value: 0x7f0402f4
			public const int silver = 2130969332;
			
			// aapt resource value: 0x7f0402f5
			public const int sinopia = 2130969333;
			
			// aapt resource value: 0x7f0402f6
			public const int skobeloff = 2130969334;
			
			// aapt resource value: 0x7f0402f7
			public const int sky_blue = 2130969335;
			
			// aapt resource value: 0x7f0402f8
			public const int sky_magenta = 2130969336;
			
			// aapt resource value: 0x7f0402f9
			public const int slate_blue = 2130969337;
			
			// aapt resource value: 0x7f0402fa
			public const int slate_gray = 2130969338;
			
			// aapt resource value: 0x7f0402fb
			public const int slime_green = 2130969339;
			
			// aapt resource value: 0x7f0402fc
			public const int smokey_gray = 2130969340;
			
			// aapt resource value: 0x7f0402fd
			public const int smokey_topaz = 2130969341;
			
			// aapt resource value: 0x7f0402fe
			public const int smoky_black = 2130969342;
			
			// aapt resource value: 0x7f0402ff
			public const int snow = 2130969343;
			
			// aapt resource value: 0x7f0403b2
			public const int soarnix_bg_gray = 2130969522;
			
			// aapt resource value: 0x7f040300
			public const int spiro_disco_ball = 2130969344;
			
			// aapt resource value: 0x7f040301
			public const int spring_bud = 2130969345;
			
			// aapt resource value: 0x7f040302
			public const int spring_green = 2130969346;
			
			// aapt resource value: 0x7f040303
			public const int steel_blue = 2130969347;
			
			// aapt resource value: 0x7f040304
			public const int stil_de_grain_yellow = 2130969348;
			
			// aapt resource value: 0x7f040305
			public const int stoplight_go_green = 2130969349;
			
			// aapt resource value: 0x7f040306
			public const int straw = 2130969350;
			
			// aapt resource value: 0x7f040307
			public const int sun_yellow = 2130969351;
			
			// aapt resource value: 0x7f040308
			public const int sunglow = 2130969352;
			
			// aapt resource value: 0x7f040309
			public const int sunrise_orange = 2130969353;
			
			// aapt resource value: 0x7f04030a
			public const int sunset = 2130969354;
			
			// aapt resource value: 0x7f04030b
			public const int sunset_orange = 2130969355;
			
			// aapt resource value: 0x7f04030c
			public const int tan = 2130969356;
			
			// aapt resource value: 0x7f04030d
			public const int tan_brown = 2130969357;
			
			// aapt resource value: 0x7f04030e
			public const int tangelo = 2130969358;
			
			// aapt resource value: 0x7f04030f
			public const int tangerine = 2130969359;
			
			// aapt resource value: 0x7f040310
			public const int tangerine_yellow = 2130969360;
			
			// aapt resource value: 0x7f040311
			public const int taupe = 2130969361;
			
			// aapt resource value: 0x7f040312
			public const int taupe_gray = 2130969362;
			
			// aapt resource value: 0x7f040313
			public const int tawny = 2130969363;
			
			// aapt resource value: 0x7f040314
			public const int tea_green = 2130969364;
			
			// aapt resource value: 0x7f040315
			public const int tea_rose = 2130969365;
			
			// aapt resource value: 0x7f040316
			public const int teal = 2130969366;
			
			// aapt resource value: 0x7f040317
			public const int teal_blue = 2130969367;
			
			// aapt resource value: 0x7f040318
			public const int teal_green = 2130969368;
			
			// aapt resource value: 0x7f040319
			public const int terra_cotta = 2130969369;
			
			// aapt resource value: 0x7f04031a
			public const int thistle = 2130969370;
			
			// aapt resource value: 0x7f04031b
			public const int thulian_pink = 2130969371;
			
			// aapt resource value: 0x7f04031c
			public const int tickle_me_pink = 2130969372;
			
			// aapt resource value: 0x7f04031d
			public const int tiffany_blue = 2130969373;
			
			// aapt resource value: 0x7f04031e
			public const int tiger_eye = 2130969374;
			
			// aapt resource value: 0x7f04031f
			public const int tiger_orange = 2130969375;
			
			// aapt resource value: 0x7f040320
			public const int timberwolf = 2130969376;
			
			// aapt resource value: 0x7f040321
			public const int titanium_yellow = 2130969377;
			
			// aapt resource value: 0x7f040322
			public const int tomato = 2130969378;
			
			// aapt resource value: 0x7f040323
			public const int toolbox = 2130969379;
			
			// aapt resource value: 0x7f040324
			public const int topaz = 2130969380;
			
			// aapt resource value: 0x7f040325
			public const int tractor_red = 2130969381;
			
			// aapt resource value: 0x7f04036e
			public const int transparent_black_hex_1 = 2130969454;
			
			// aapt resource value: 0x7f040377
			public const int transparent_black_hex_10 = 2130969463;
			
			// aapt resource value: 0x7f040378
			public const int transparent_black_hex_11 = 2130969464;
			
			// aapt resource value: 0x7f040379
			public const int transparent_black_hex_12 = 2130969465;
			
			// aapt resource value: 0x7f04037a
			public const int transparent_black_hex_13 = 2130969466;
			
			// aapt resource value: 0x7f04037b
			public const int transparent_black_hex_14 = 2130969467;
			
			// aapt resource value: 0x7f04037c
			public const int transparent_black_hex_15 = 2130969468;
			
			// aapt resource value: 0x7f04036f
			public const int transparent_black_hex_2 = 2130969455;
			
			// aapt resource value: 0x7f040370
			public const int transparent_black_hex_3 = 2130969456;
			
			// aapt resource value: 0x7f040371
			public const int transparent_black_hex_4 = 2130969457;
			
			// aapt resource value: 0x7f040372
			public const int transparent_black_hex_5 = 2130969458;
			
			// aapt resource value: 0x7f040373
			public const int transparent_black_hex_6 = 2130969459;
			
			// aapt resource value: 0x7f040374
			public const int transparent_black_hex_7 = 2130969460;
			
			// aapt resource value: 0x7f040375
			public const int transparent_black_hex_8 = 2130969461;
			
			// aapt resource value: 0x7f040376
			public const int transparent_black_hex_9 = 2130969462;
			
			// aapt resource value: 0x7f04037e
			public const int transparent_black_percent_10 = 2130969470;
			
			// aapt resource value: 0x7f04037f
			public const int transparent_black_percent_15 = 2130969471;
			
			// aapt resource value: 0x7f040380
			public const int transparent_black_percent_20 = 2130969472;
			
			// aapt resource value: 0x7f040381
			public const int transparent_black_percent_25 = 2130969473;
			
			// aapt resource value: 0x7f040382
			public const int transparent_black_percent_30 = 2130969474;
			
			// aapt resource value: 0x7f040383
			public const int transparent_black_percent_35 = 2130969475;
			
			// aapt resource value: 0x7f040384
			public const int transparent_black_percent_40 = 2130969476;
			
			// aapt resource value: 0x7f040385
			public const int transparent_black_percent_45 = 2130969477;
			
			// aapt resource value: 0x7f04037d
			public const int transparent_black_percent_5 = 2130969469;
			
			// aapt resource value: 0x7f040386
			public const int transparent_black_percent_50 = 2130969478;
			
			// aapt resource value: 0x7f040387
			public const int transparent_black_percent_55 = 2130969479;
			
			// aapt resource value: 0x7f040388
			public const int transparent_black_percent_60 = 2130969480;
			
			// aapt resource value: 0x7f040389
			public const int transparent_black_percent_65 = 2130969481;
			
			// aapt resource value: 0x7f04038a
			public const int transparent_black_percent_70 = 2130969482;
			
			// aapt resource value: 0x7f04038b
			public const int transparent_black_percent_75 = 2130969483;
			
			// aapt resource value: 0x7f04038c
			public const int transparent_black_percent_80 = 2130969484;
			
			// aapt resource value: 0x7f04038d
			public const int transparent_black_percent_85 = 2130969485;
			
			// aapt resource value: 0x7f04038e
			public const int transparent_black_percent_90 = 2130969486;
			
			// aapt resource value: 0x7f04038f
			public const int transparent_black_percent_95 = 2130969487;
			
			// aapt resource value: 0x7f040390
			public const int transparent_white_hex_1 = 2130969488;
			
			// aapt resource value: 0x7f040399
			public const int transparent_white_hex_10 = 2130969497;
			
			// aapt resource value: 0x7f04039a
			public const int transparent_white_hex_11 = 2130969498;
			
			// aapt resource value: 0x7f04039b
			public const int transparent_white_hex_12 = 2130969499;
			
			// aapt resource value: 0x7f04039c
			public const int transparent_white_hex_13 = 2130969500;
			
			// aapt resource value: 0x7f04039d
			public const int transparent_white_hex_14 = 2130969501;
			
			// aapt resource value: 0x7f04039e
			public const int transparent_white_hex_15 = 2130969502;
			
			// aapt resource value: 0x7f040391
			public const int transparent_white_hex_2 = 2130969489;
			
			// aapt resource value: 0x7f040392
			public const int transparent_white_hex_3 = 2130969490;
			
			// aapt resource value: 0x7f040393
			public const int transparent_white_hex_4 = 2130969491;
			
			// aapt resource value: 0x7f040394
			public const int transparent_white_hex_5 = 2130969492;
			
			// aapt resource value: 0x7f040395
			public const int transparent_white_hex_6 = 2130969493;
			
			// aapt resource value: 0x7f040396
			public const int transparent_white_hex_7 = 2130969494;
			
			// aapt resource value: 0x7f040397
			public const int transparent_white_hex_8 = 2130969495;
			
			// aapt resource value: 0x7f040398
			public const int transparent_white_hex_9 = 2130969496;
			
			// aapt resource value: 0x7f0403a0
			public const int transparent_white_percent_10 = 2130969504;
			
			// aapt resource value: 0x7f0403a1
			public const int transparent_white_percent_15 = 2130969505;
			
			// aapt resource value: 0x7f0403a2
			public const int transparent_white_percent_20 = 2130969506;
			
			// aapt resource value: 0x7f0403a3
			public const int transparent_white_percent_25 = 2130969507;
			
			// aapt resource value: 0x7f0403a4
			public const int transparent_white_percent_30 = 2130969508;
			
			// aapt resource value: 0x7f0403a5
			public const int transparent_white_percent_35 = 2130969509;
			
			// aapt resource value: 0x7f0403a6
			public const int transparent_white_percent_40 = 2130969510;
			
			// aapt resource value: 0x7f0403a7
			public const int transparent_white_percent_45 = 2130969511;
			
			// aapt resource value: 0x7f04039f
			public const int transparent_white_percent_5 = 2130969503;
			
			// aapt resource value: 0x7f0403a8
			public const int transparent_white_percent_50 = 2130969512;
			
			// aapt resource value: 0x7f0403a9
			public const int transparent_white_percent_55 = 2130969513;
			
			// aapt resource value: 0x7f0403aa
			public const int transparent_white_percent_60 = 2130969514;
			
			// aapt resource value: 0x7f0403ab
			public const int transparent_white_percent_65 = 2130969515;
			
			// aapt resource value: 0x7f0403ac
			public const int transparent_white_percent_70 = 2130969516;
			
			// aapt resource value: 0x7f0403ad
			public const int transparent_white_percent_75 = 2130969517;
			
			// aapt resource value: 0x7f0403ae
			public const int transparent_white_percent_80 = 2130969518;
			
			// aapt resource value: 0x7f0403af
			public const int transparent_white_percent_85 = 2130969519;
			
			// aapt resource value: 0x7f0403b0
			public const int transparent_white_percent_90 = 2130969520;
			
			// aapt resource value: 0x7f0403b1
			public const int transparent_white_percent_95 = 2130969521;
			
			// aapt resource value: 0x7f040326
			public const int tron_blue = 2130969382;
			
			// aapt resource value: 0x7f040327
			public const int tropical_rain_forest = 2130969383;
			
			// aapt resource value: 0x7f040328
			public const int true_blue = 2130969384;
			
			// aapt resource value: 0x7f040329
			public const int tufts_blue = 2130969385;
			
			// aapt resource value: 0x7f04032a
			public const int tulip_pink = 2130969386;
			
			// aapt resource value: 0x7f04032b
			public const int tumbleweed = 2130969387;
			
			// aapt resource value: 0x7f04032c
			public const int turkish_rose = 2130969388;
			
			// aapt resource value: 0x7f04032d
			public const int turquoise = 2130969389;
			
			// aapt resource value: 0x7f04032e
			public const int turquoise_blue = 2130969390;
			
			// aapt resource value: 0x7f04032f
			public const int turquoise_green = 2130969391;
			
			// aapt resource value: 0x7f040330
			public const int tuscan_red = 2130969392;
			
			// aapt resource value: 0x7f040331
			public const int twilight_lavender = 2130969393;
			
			// aapt resource value: 0x7f040332
			public const int tyrian_purple = 2130969394;
			
			// aapt resource value: 0x7f040333
			public const int ua_blue = 2130969395;
			
			// aapt resource value: 0x7f040334
			public const int ua_red = 2130969396;
			
			// aapt resource value: 0x7f040335
			public const int ube = 2130969397;
			
			// aapt resource value: 0x7f040336
			public const int ucla_blue = 2130969398;
			
			// aapt resource value: 0x7f040337
			public const int ucla_gold = 2130969399;
			
			// aapt resource value: 0x7f040338
			public const int ufo_green = 2130969400;
			
			// aapt resource value: 0x7f040339
			public const int ultra_pink = 2130969401;
			
			// aapt resource value: 0x7f04033a
			public const int ultramarine = 2130969402;
			
			// aapt resource value: 0x7f04033b
			public const int ultramarine_blue = 2130969403;
			
			// aapt resource value: 0x7f04033c
			public const int umber = 2130969404;
			
			// aapt resource value: 0x7f04033d
			public const int united_nations_blue = 2130969405;
			
			// aapt resource value: 0x7f04033e
			public const int university_of_california_gold = 2130969406;
			
			// aapt resource value: 0x7f04033f
			public const int unmellow_yellow = 2130969407;
			
			// aapt resource value: 0x7f040340
			public const int up_forest_green = 2130969408;
			
			// aapt resource value: 0x7f040341
			public const int up_maroon = 2130969409;
			
			// aapt resource value: 0x7f040342
			public const int upsdell_red = 2130969410;
			
			// aapt resource value: 0x7f040343
			public const int urobilin = 2130969411;
			
			// aapt resource value: 0x7f040344
			public const int utah_crimson = 2130969412;
			
			// aapt resource value: 0x7f040345
			public const int valentine_red = 2130969413;
			
			// aapt resource value: 0x7f040346
			public const int vampire_gray = 2130969414;
			
			// aapt resource value: 0x7f040347
			public const int vanilla = 2130969415;
			
			// aapt resource value: 0x7f040348
			public const int vegas_gold = 2130969416;
			
			// aapt resource value: 0x7f040349
			public const int velvet_maroon = 2130969417;
			
			// aapt resource value: 0x7f04034a
			public const int venetian_red = 2130969418;
			
			// aapt resource value: 0x7f04034b
			public const int venom_green = 2130969419;
			
			// aapt resource value: 0x7f04034c
			public const int verdigris = 2130969420;
			
			// aapt resource value: 0x7f04034d
			public const int veronica = 2130969421;
			
			// aapt resource value: 0x7f04034e
			public const int viola_purple = 2130969422;
			
			// aapt resource value: 0x7f04034f
			public const int violet = 2130969423;
			
			// aapt resource value: 0x7f040350
			public const int violet_blue = 2130969424;
			
			// aapt resource value: 0x7f040351
			public const int violet_red = 2130969425;
			
			// aapt resource value: 0x7f040352
			public const int viridian = 2130969426;
			
			// aapt resource value: 0x7f040353
			public const int vivid_auburn = 2130969427;
			
			// aapt resource value: 0x7f040354
			public const int vivid_burgundy = 2130969428;
			
			// aapt resource value: 0x7f040355
			public const int vivid_cerise = 2130969429;
			
			// aapt resource value: 0x7f040356
			public const int vivid_tangerine = 2130969430;
			
			// aapt resource value: 0x7f040357
			public const int vivid_violet = 2130969431;
			
			// aapt resource value: 0x7f040358
			public const int warm_black = 2130969432;
			
			// aapt resource value: 0x7f040359
			public const int water = 2130969433;
			
			// aapt resource value: 0x7f04035a
			public const int watermelon_pink = 2130969434;
			
			// aapt resource value: 0x7f04035b
			public const int wenge = 2130969435;
			
			// aapt resource value: 0x7f04035c
			public const int wheat = 2130969436;
			
			// aapt resource value: 0x7f04035d
			public const int white = 2130969437;
			
			// aapt resource value: 0x7f04035e
			public const int white_smoke = 2130969438;
			
			// aapt resource value: 0x7f04035f
			public const int wild_blue_yonder = 2130969439;
			
			// aapt resource value: 0x7f040360
			public const int wild_strawberry = 2130969440;
			
			// aapt resource value: 0x7f040361
			public const int wild_watermelon = 2130969441;
			
			// aapt resource value: 0x7f040362
			public const int wine = 2130969442;
			
			// aapt resource value: 0x7f040363
			public const int wiseria_purple = 2130969443;
			
			// aapt resource value: 0x7f040364
			public const int wisteria = 2130969444;
			
			// aapt resource value: 0x7f040365
			public const int wood = 2130969445;
			
			// aapt resource value: 0x7f040366
			public const int xanadu = 2130969446;
			
			// aapt resource value: 0x7f040367
			public const int yale_blue = 2130969447;
			
			// aapt resource value: 0x7f040368
			public const int yellow = 2130969448;
			
			// aapt resource value: 0x7f040369
			public const int yellow_green = 2130969449;
			
			// aapt resource value: 0x7f04036a
			public const int yellow_orange = 2130969450;
			
			// aapt resource value: 0x7f04036b
			public const int zaffre = 2130969451;
			
			// aapt resource value: 0x7f04036c
			public const int zinnwaldite_brown = 2130969452;
			
			// aapt resource value: 0x7f04036d
			public const int zombie_green = 2130969453;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg_button_bluebutton = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bg_innerline_horizontal = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bg_innerline_vertical = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg_relativelayout_grayround = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bglist_blue_grayrounded = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bglist_blue_grayrounded_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int menu_dropdown_panel = 2130837511;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080018
			public const int cell_img = 2131230744;
			
			// aapt resource value: 0x7f080017
			public const int cell_text = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int cnavsview = 2131230742;
			
			// aapt resource value: 0x7f080003
			public const int login_innerline_1 = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int login_logo_imagview = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int login_panel_relativelayout = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int login_root_relativelayout = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int test_bandwidth_label = 2131230731;
			
			// aapt resource value: 0x7f080015
			public const int test_console_textview = 2131230741;
			
			// aapt resource value: 0x7f080010
			public const int test_datarate_checkbox = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int test_datarate_label = 2131230735;
			
			// aapt resource value: 0x7f080006
			public const int test_devicelist = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int test_distance_checkbox = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int test_distance_spinner = 2131230732;
			
			// aapt resource value: 0x7f080004
			public const int test_element = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int test_listparent = 2131230725;
			
			// aapt resource value: 0x7f08001a
			public const int test_multiappsupport_checkbox = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int test_multiappsupport_label = 2131230745;
			
			// aapt resource value: 0x7f08000e
			public const int test_resource_checkbox = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int test_resource_label = 2131230733;
			
			// aapt resource value: 0x7f080012
			public const int test_roundtrip_checkbox = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int test_roundtrip_label = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int test_sendvirtualrequest = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int test_starttest_but = 2131230739;
			
			// aapt resource value: 0x7f080008
			public const int test_status_connected = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int test_status_role = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int test_testoptions = 2131230729;
			
			// aapt resource value: 0x7f08001c
			public const int test_testroundtrip_checkbox = 2131230748;
			
			// aapt resource value: 0x7f08001b
			public const int test_testroundtrip_label = 2131230747;
			
			// aapt resource value: 0x7f080020
			public const int test_testsendheader_checkbox = 2131230752;
			
			// aapt resource value: 0x7f08001f
			public const int test_testsendheader_label = 2131230751;
			
			// aapt resource value: 0x7f08001e
			public const int test_testsendmultipackets_checkbox = 2131230750;
			
			// aapt resource value: 0x7f08001d
			public const int test_testsendmultipackets_label = 2131230749;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ClusterTest_Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Graffiti_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int listCellLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SampleScratcher_main = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int hello = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Np2pStyle = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CanavsView = new int[] {
					16842904,
					16843087,
					2130771968};
			
			// aapt resource value: 1
			public const int CanavsView_android_text = 1;
			
			// aapt resource value: 0
			public const int CanavsView_android_textColor = 0;
			
			// aapt resource value: 2
			public const int CanavsView_extraInformation = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
